export const questionAnswers = [
  {
    _id: "01",
    question: "This is my chosen <br /> spirit sandwich",
    questionIndex: 1,
    answers: [
      { answer: "Bratwurst", answerIndex: 1, labelWord: "A" },
      { answer: "BLT", answerIndex: 2, labelWord: "B" },
      { answer: "Poboy", answerIndex: 3, labelWord: "C" },
      { answer: "MonteCristo", answerIndex: 4, labelWord: "D" },
      { answer: "Reuben", answerIndex: 5, labelWord: "E" },
      { answer: "Tunamelt", answerIndex: 6, labelWord: "F" },
      { answer: "Chili Dog", answerIndex: 7, labelWord: "G" },
      { answer: "Shwarma", answerIndex: 8, labelWord: "H" },
      { answer: "Club", answerIndex: 9, labelWord: "I" },
      { answer: "French Dip ", answerIndex: 10, labelWord: "J" },
      { answer: "Spam On White", answerIndex: 11, labelWord: "K" },
      { answer: "Chili Dog ", answerIndex: 12, labelWord: "L" },
      { answer: "Ceasar Wrap", answerIndex: 13, labelWord: "M" },
      { answer: "Sloppy Jo ", answerIndex: 14, labelWord: "N" },
      { answer: "Cheese Steak", answerIndex: 15, labelWord: "O" },
      { answer: "Grilled Cheese", answerIndex: 16, labelWord: "P" },
      { answer: "Lox & Bagel", answerIndex: 17, labelWord: "Q" },
      { answer: "PB&J", answerIndex: 18, labelWord: "R" },
      { answer: "Gyro", answerIndex: 19, labelWord: "S" },
      { answer: "BahnMi", answerIndex: 20, labelWord: "T" },
      { answer: "BLT", answerIndex: 21, labelWord: "U" },
      { answer: "Burger", answerIndex: 22, labelWord: "V" },
      { answer: "MonteCristo", answerIndex: 23, labelWord: "W" },
      { answer: "+/- Mayo ", answerIndex: 24, labelWord: "X" },
      { answer: "Tunamelt", answerIndex: 25, labelWord: "Y" },
      { answer: "+/- Mustard ", answerIndex: 26, labelWord: "Z" },
    ],
  },
  {
    _id: "02",
    question: "I identify with this <br /> species",
    questionIndex: 2,
    answers: [
      { answer: "Bratwurst", answerIndex: 1, labelWord: "A" },
      { answer: "BLT", answerIndex: 1, labelWord: "B" },
      { answer: "Poboy", answerIndex: 3, labelWord: "C" },
      { answer: "MonteCristo", answerIndex: 4, labelWord: "D" },
      { answer: "Reuben", answerIndex: 5, labelWord: "E" },
      { answer: "Tunamelt", answerIndex: 6, labelWord: "F" },
      { answer: "Chili Dog", answerIndex: 7, labelWord: "G" },
      { answer: "Shwarma", answerIndex: 8, labelWord: "H" },
      { answer: "Club", answerIndex: 9, labelWord: "I" },
      { answer: "French Dip ", answerIndex: 10, labelWord: "J" },
      { answer: "Spam On White", answerIndex: 11, labelWord: "K" },
      { answer: "Chili Dog ", answerIndex: 12, labelWord: "L" },
      { answer: "Ceasar Wrap", answerIndex: 13, labelWord: "M" },
      { answer: "Sloppy Jo ", answerIndex: 14, labelWord: "N" },
      { answer: "Cheese Steak", answerIndex: 15, labelWord: "O" },
      { answer: "Grilled Cheese", answerIndex: 16, labelWord: "P" },
      { answer: "Lox & Bagel", answerIndex: 17, labelWord: "Q" },
      { answer: "PB&J", answerIndex: 18, labelWord: "R" },
      { answer: "Gyro", answerIndex: 19, labelWord: "S" },
      { answer: "BahnMi", answerIndex: 20, labelWord: "T" },
      { answer: "BLT", answerIndex: 21, labelWord: "U" },
      { answer: "Burger", answerIndex: 22, labelWord: "V" },
      { answer: "MonteCristo", answerIndex: 23, labelWord: "W" },
      { answer: "+/- Mayo ", answerIndex: 24, labelWord: "X" },
      { answer: "Tunamelt", answerIndex: 25, labelWord: "Y" },
      { answer: "+/- Mustard ", answerIndex: 26, labelWord: "Z" },
    ],
  },
  {
    _id: "03",
    question: "I would like to add, subtract or replace these body parts",
    questionIndex: 2,
    answers: [
      { answer: "Bratwurst", answerIndex: 1, labelWord: "A" },
      { answer: "BLT", answerIndex: 1, labelWord: "B" },
      { answer: "Poboy", answerIndex: 3, labelWord: "C" },
      { answer: "MonteCristo", answerIndex: 4, labelWord: "D" },
      { answer: "Reuben", answerIndex: 5, labelWord: "E" },
      { answer: "Tunamelt", answerIndex: 6, labelWord: "F" },
      { answer: "Chili Dog", answerIndex: 7, labelWord: "G" },
      { answer: "Shwarma", answerIndex: 8, labelWord: "H" },
      { answer: "Club", answerIndex: 9, labelWord: "I" },
      { answer: "French Dip ", answerIndex: 10, labelWord: "J" },
      { answer: "Spam On White", answerIndex: 11, labelWord: "K" },
      { answer: "Chili Dog ", answerIndex: 12, labelWord: "L" },
      { answer: "Ceasar Wrap", answerIndex: 13, labelWord: "M" },
      { answer: "Sloppy Jo ", answerIndex: 14, labelWord: "N" },
      { answer: "Cheese Steak", answerIndex: 15, labelWord: "O" },
      { answer: "Grilled Cheese", answerIndex: 16, labelWord: "P" },
      { answer: "Lox & Bagel", answerIndex: 17, labelWord: "Q" },
      { answer: "PB&J", answerIndex: 18, labelWord: "R" },
      { answer: "Gyro", answerIndex: 19, labelWord: "S" },
      { answer: "BahnMi", answerIndex: 20, labelWord: "T" },
      { answer: "BLT", answerIndex: 21, labelWord: "U" },
      { answer: "Burger", answerIndex: 22, labelWord: "V" },
      { answer: "MonteCristo", answerIndex: 23, labelWord: "W" },
      { answer: "+/- Mayo ", answerIndex: 24, labelWord: "X" },
      { answer: "Tunamelt", answerIndex: 25, labelWord: "Y" },
      { answer: "+/- Mustard ", answerIndex: 26, labelWord: "Z" },
    ],
  },
  {
    _id: "04",
    question: "These body parts <br /> turn me on!",
    questionIndex: 4,
    answers: [
      { answer: "Bratwurst", answerIndex: 1, labelWord: "A" },
      { answer: "BLT", answerIndex: 1, labelWord: "B" },
      { answer: "Poboy", answerIndex: 3, labelWord: "C" },
      { answer: "MonteCristo", answerIndex: 4, labelWord: "D" },
      { answer: "Reuben", answerIndex: 5, labelWord: "E" },
      { answer: "Tunamelt", answerIndex: 6, labelWord: "F" },
      { answer: "Chili Dog", answerIndex: 7, labelWord: "G" },
      { answer: "Shwarma", answerIndex: 8, labelWord: "H" },
      { answer: "Club", answerIndex: 9, labelWord: "I" },
      { answer: "French Dip ", answerIndex: 10, labelWord: "J" },
      { answer: "Spam On White", answerIndex: 11, labelWord: "K" },
      { answer: "Chili Dog ", answerIndex: 12, labelWord: "L" },
      { answer: "Ceasar Wrap", answerIndex: 13, labelWord: "M" },
      { answer: "Sloppy Jo ", answerIndex: 14, labelWord: "N" },
      { answer: "Cheese Steak", answerIndex: 15, labelWord: "O" },
      { answer: "Grilled Cheese", answerIndex: 16, labelWord: "P" },
      { answer: "Lox & Bagel", answerIndex: 17, labelWord: "Q" },
      { answer: "PB&J", answerIndex: 18, labelWord: "R" },
      { answer: "Gyro", answerIndex: 19, labelWord: "S" },
      { answer: "BahnMi", answerIndex: 20, labelWord: "T" },
      { answer: "BLT", answerIndex: 21, labelWord: "U" },
      { answer: "Burger", answerIndex: 22, labelWord: "V" },
      { answer: "MonteCristo", answerIndex: 23, labelWord: "W" },
      { answer: "+/- Mayo ", answerIndex: 24, labelWord: "X" },
      { answer: "Tunamelt", answerIndex: 25, labelWord: "Y" },
      { answer: "+/- Mustard ", answerIndex: 26, labelWord: "Z" },
    ],
  },
  {
    _id: "05",
    question: "This neurotic or existential <br /> fear haunts me",
    questionIndex: 5,
    answers: [
      { answer: "Bratwurst", answerIndex: 1, labelWord: "A" },
      { answer: "BLT", answerIndex: 1, labelWord: "B" },
      { answer: "Poboy", answerIndex: 3, labelWord: "C" },
      { answer: "MonteCristo", answerIndex: 4, labelWord: "D" },
      { answer: "Reuben", answerIndex: 5, labelWord: "E" },
      { answer: "Tunamelt", answerIndex: 6, labelWord: "F" },
      { answer: "Chili Dog", answerIndex: 7, labelWord: "G" },
      { answer: "Shwarma", answerIndex: 8, labelWord: "H" },
      { answer: "Club", answerIndex: 9, labelWord: "I" },
      { answer: "French Dip ", answerIndex: 10, labelWord: "J" },
      { answer: "Spam On White", answerIndex: 11, labelWord: "K" },
      { answer: "Chili Dog ", answerIndex: 12, labelWord: "L" },
      { answer: "Ceasar Wrap", answerIndex: 13, labelWord: "M" },
      { answer: "Sloppy Jo ", answerIndex: 14, labelWord: "N" },
      { answer: "Cheese Steak", answerIndex: 15, labelWord: "O" },
      { answer: "Grilled Cheese", answerIndex: 16, labelWord: "P" },
      { answer: "Lox & Bagel", answerIndex: 17, labelWord: "Q" },
      { answer: "PB&J", answerIndex: 18, labelWord: "R" },
      { answer: "Gyro", answerIndex: 19, labelWord: "S" },
      { answer: "BahnMi", answerIndex: 20, labelWord: "T" },
      { answer: "BLT", answerIndex: 21, labelWord: "U" },
      { answer: "Burger", answerIndex: 22, labelWord: "V" },
      { answer: "MonteCristo", answerIndex: 23, labelWord: "W" },
      { answer: "+/- Mayo ", answerIndex: 24, labelWord: "X" },
      { answer: "Tunamelt", answerIndex: 25, labelWord: "Y" },
      { answer: "+/- Mustard ", answerIndex: 26, labelWord: "Z" },
    ],
  },
];
