export const questionAnswers = [
  {
    _id: "01",
    question: "I identify with this species:",
    answers: [
      { answer: "Homo Sapien", labelWord: "A" },
      { answer: "Mermaid", labelWord: "B" },
      { answer: "Leprechaun  ", labelWord: "C" },
      { answer: "Unicorn ", labelWord: "D" },
      { answer: "Banshee", labelWord: "E" },
      { answer: "Gnome", labelWord: "F" },
      { answer: "Klingon", labelWord: "G" },
      { answer: "Dragon", labelWord: "H" },
      { answer: "Vampire", labelWord: "I" },
      { answer: "Neanderthal ", labelWord: "J" },
      { answer: "Zombie", labelWord: "K" },
      { answer: "Minotaur", labelWord: "L" },
      { answer: "Cyclops", labelWord: "M" },
      { answer: "+ MYOB", labelWord: "N" },
      { answer: "Sasquatch", labelWord: "O" },
      { answer: "Just add Mayo", labelWord: "P" },
    ],
  },
  {
    _id: "02",
    question: "This is my spirit sandwich: ",
    answers: [
      { answer: "Po-Boy ", labelWord: "A" },
      { answer: "BLT", labelWord: "B" },
      { answer: "Reuben", labelWord: "C" },
      { answer: "Monte Cristo", labelWord: "D" },
      { answer: "Chili Dog", labelWord: "E" },
      { answer: "French Dip", labelWord: "F" },
      { answer: "Cesaer Wrap", labelWord: "G" },
      { answer: "Sloppy Jo", labelWord: "H" },
      { answer: "Cheese Steak", labelWord: "I" },
      { answer: "Tuna Melt", labelWord: "J" },
      { answer: "Lox & Bagel", labelWord: "K" },
      { answer: "PB & J", labelWord: "L" },
      { answer: "Gyro", labelWord: "M" },
      { answer: "+ MYOB", labelWord: "N" },
      { answer: "Grilled Cheese", labelWord: "O" },
      { answer: "Just add Mustard ", labelWord: "P" },
    ],
  },
  {
    _id: "03",
    question: "I would like to add, subtract or <br> replace these body parts:",
    answers: [
      { answer: "Tummy", labelWord: "A" },
      { answer: "Boobs", labelWord: "B" },
      { answer: "Ear Lobes", labelWord: "C" },
      { answer: "Rear Dimples", labelWord: "D" },
      { answer: "Vajayjay", labelWord: "E" },
      { answer: "Hairline", labelWord: "F" },
      { answer: "Thighs", labelWord: "G" },
      { answer: "Taint", labelWord: "H" },
      { answer: "Lips", labelWord: "I" },
      { answer: "Arm Pits", labelWord: "J" },
      { answer: "Peepers", labelWord: "K" },
      { answer: "Tootsies", labelWord: "L" },
      { answer: "Keister", labelWord: "M" },
      { answer: "+ MYOB", labelWord: "N" },
      { answer: "Pecker", labelWord: "O" },
      { answer: "Just add Relish ", labelWord: "P" },
    ],
  },
  {
    _id: "04",
    question: "These body parts make me <br> wild with desire: ",
    answers: [
      { answer: "Arm Pits ", labelWord: "A" },
      { answer: "Rear Dimples", labelWord: "B" },
      { answer: "Keister", labelWord: "C" },
      { answer: "Pecker ", labelWord: "D" },
      { answer: "Tummy", labelWord: "E" },
      { answer: "Thighs", labelWord: "F" },
      { answer: "Rear Dimples", labelWord: "G" },
      { answer: "Tootsies", labelWord: "H" },
      { answer: "Vajayjay", labelWord: "I" },
      { answer: "Peepers", labelWord: "J" },
      { answer: "Boobs", labelWord: "K" },
      { answer: "Temples", labelWord: "L" },
      { answer: "Ear Lobes", labelWord: "M" },
      { answer: "+ MYOB", labelWord: "N" },
      { answer: "Lips", labelWord: "O" },
      { answer: "Just add Salsa", labelWord: "P" },
    ],
  },
  {
    _id: "05",
    question: "This existential fear or <br> neurotic worry haunts me: ",
    answers: [
      { answer: "My life is absurd.", labelWord: "A" },
      { answer: "I need booze", labelWord: "B" },
      { answer: "There is no essential self.", labelWord: "C" },
      { answer: "I count the sidewalk cracks ", labelWord: "D" },
      { answer: "Anything can happen at anytime.", labelWord: "E" },
      { answer: "There is something living under my bed my bed", labelWord: "F" },
      { answer: "I am alone and I am alone", labelWord: "G" },
      { answer: "Hypotheitcal stiutaion anxiety", labelWord: "H" },
      { answer: "I only want to sit on the couch", labelWord: "I" },
      { answer: "My food is touching each other", labelWord: "J" },
      { answer: "the next ice age is near", labelWord: "K" },
      { answer: "Dust bunnies are in the corners my bed", labelWord: "L" },
      { answer: "I fart too much", labelWord: "M" },
      { answer: "+ MYOB", labelWord: "N" },
      { answer: "My taxes are due EVERY year", labelWord: "O" },
      { answer: "Just add Pickles", labelWord: "P" },
    ],
  },
];
