export const questionAnswers = [
  {
    _id: "01",
    question: "I identify with <br/> this species:",
    answers: [
      { answer: "Homo Sapien", labelWord: "A" },
      { answer: "Big Foot", labelWord: "B" },
      { answer: "Leprechaun", labelWord: "C" },
      { answer: "Salamander", labelWord: "D" },
      { answer: "Fruit Fly", labelWord: "E" },
      { answer: "Mermaid", labelWord: "F" },
      { answer: "Banshee", labelWord: "G" },
      { answer: "Unicorn", labelWord: "H" },
      { answer: "Kingon", labelWord: "I" },
      { answer: "Gnome ", labelWord: "J" },
      { answer: "Vampire", labelWord: "K" },
      { answer: "Black Widow", labelWord: "L" },
      { answer: "Wood Nympth", labelWord: "M" },
      { answer: "Octopus", labelWord: "N" },
      { answer: "Neanderthal", labelWord: "O" },
      { answer: "Elf", labelWord: "P" },
      { answer: "Minotaur", labelWord: "Q" },
      { answer: "Dragon", labelWord: "R" },
      { answer: "Tribble", labelWord: "S" },
      { answer: "Slyph", labelWord: "T" },
      { answer: "Jawa", labelWord: "U" },
      { answer: "Ghost", labelWord: "V" },
      { answer: "Cyclops", labelWord: "W" },
      { answer: "+ Mayo ", labelWord: "X" },
      { answer: "Zombie", labelWord: "Y" },
      { answer: "+Mustard", labelWord: "Z" },
    ],
  },
  {
    _id: "02",
    question: "This is my  <br /> spirit sandwich:",
    answers: [
      { answer: "Bratwurst", labelWord: "A" },
      { answer: "BLT", labelWord: "B" },
      { answer: "Poboy", labelWord: "C" },
      { answer: "MonteCristo", labelWord: "D" },
      { answer: "Reuben", labelWord: "E" },
      { answer: "Tunamelt", labelWord: "F" },
      { answer: "Chili Dog", labelWord: "G" },
      { answer: "Shwarma", labelWord: "H" },
      { answer: "Club", labelWord: "I" },
      { answer: "French Dip ", labelWord: "J" },
      { answer: "Spam On White", labelWord: "K" },
      { answer: "Chili Dog ", labelWord: "L" },
      { answer: "Ceasar Wrap", labelWord: "M" },
      { answer: "Sloppy Jo ", labelWord: "N" },
      { answer: "Cheese Steak", labelWord: "O" },
      { answer: "Grilled Cheese", labelWord: "P" },
      { answer: "Lox & Bagel", labelWord: "Q" },
      { answer: "PB&J", labelWord: "R" },
      { answer: "Gyro", labelWord: "S" },
      { answer: "BahnMi", labelWord: "T" },
      { answer: "BLT", labelWord: "U" },
      { answer: "Burger", labelWord: "V" },
      { answer: "MonteCristo", labelWord: "W" },
      { answer: "+ Mayo ", labelWord: "X" },
      { answer: "BBQ on a bun", labelWord: "Y" },
      { answer: "+ Mustard ", labelWord: "Z" },
    ],
  },
  {
    _id: "03",
    question: "I would like to add, subtract or replace these body parts: ",
    answers: [
      { answer: "Tummy", labelWord: "A" },
      { answer: "Boobs", labelWord: "B" },
      { answer: "Ear lobes", labelWord: "C" },
      { answer: "Belly button", labelWord: "D" },
      { answer: "Knee caps", labelWord: "E" },
      { answer: "Tunamelt", labelWord: "F" },
      { answer: "Vajayjay", labelWord: "G" },
      { answer: "Knuckles", labelWord: "H" },
      { answer: "Thighs", labelWord: "I" },
      { answer: "Decolletage", labelWord: "J" },
      { answer: "Lips", labelWord: "K" },
      { answer: "Rear dimples", labelWord: "L" },
      { answer: "Peepers", labelWord: "M" },
      { answer: "Adam’s apple", labelWord: "N" },
      { answer: "Keister", labelWord: "O" },
      { answer: "Taint", labelWord: "P" },
      { answer: "Hairline", labelWord: "Q" },
      { answer: "Wrists", labelWord: "R" },
      { answer: "Tootsies", labelWord: "S" },
      { answer: "Armpits", labelWord: "T" },
      { answer: "Pecker", labelWord: "U" },
      { answer: "+Mayo", labelWord: "V" },
      { answer: "Elbow", labelWord: "W" },
      { answer: "+ Mustard ", labelWord: "X" },
    ],
  },
  {
    _id: "04",
    question: "These body parts make me <br /> wild  with desire!:",
    answers: [
      { answer: "Armpits", labelWord: "A" },
      { answer: "Lips", labelWord: "B" },
      { answer: "Elbow", labelWord: "C" },
      { answer: "Tootsies", labelWord: "D" },
      { answer: "Ear lobes", labelWord: "E" },
      { answer: "Cahones", labelWord: "F" },
      { answer: "Boobs", labelWord: "G" },
      { answer: "Vajayjay", labelWord: "H" },
      { answer: "Knuckles", labelWord: "I" },
      { answer: "Knee caps", labelWord: "J" },
      { answer: "Pecker", labelWord: "K" },
      { answer: "Adams apple", labelWord: "L" },
      { answer: "Eyelashes", labelWord: "M" },
      { answer: "Decolletage", labelWord: "N" },
      { answer: "Butt dimples", labelWord: "O" },
      { answer: "Gray matter", labelWord: "P" },
      { answer: "Tummy", labelWord: "Q" },
      { answer: "Belly button", labelWord: "R" },
      { answer: "Taint", labelWord: "S" },
      { answer: "Peepers", labelWord: "T" },
      { answer: "Keister", labelWord: "U" },
      { answer: "+Mayo", labelWord: "V" },
      { answer: "Thighs", labelWord: "W" },
      { answer: "+ Mustard", labelWord: "X" },
    ],
  },
  {
    _id: "05",
    question: "This neurotic or existential <br /> fear haunts me",
    answers: [
      { answer: "My life is absurd", labelWord: "A" },
      { answer: "I worry therefore I am", labelWord: "B" },
      { answer: "There is no essential self", labelWord: "C" },
      { answer: "My bellbutton is fascinating", labelWord: "D" },
      { answer: "I count the cracks in the sidewalk", labelWord: "E" },
      { answer: "How many tons do I need to lose?", labelWord: "F" },
      { answer: "Anything could happen at anytime", labelWord: "G" },
      { answer: "My taxes are due EVERY year", labelWord: "H" },
      { answer: "I am gonna die", labelWord: "I" },
      { answer: "My food is touching each other", labelWord: "J" },
      { answer: "I am alone and I am alone", labelWord: "K" },
      { answer: "I can’t remember a thing", labelWord: "L" },
      { answer: "I hate everyone i ever met", labelWord: "M" },
      { answer: "To make or not to make my bed", labelWord: "N" },
      { answer: "I only want to sit on the couch", labelWord: "O" },
      { answer: "There is something living under my bed", labelWord: "P" },
      { answer: "The next ice age is near", labelWord: "Q" },
      { answer: "I need booze", labelWord: "R" },
      { answer: "There are dust bunnies in the corners", labelWord: "S" },
      { answer: "Dread is my mantra", labelWord: "T" },
      { answer: "I fart too much", labelWord: "U" },
      { answer: "+ Mayo", labelWord: "V" },
      { answer: "Hypothetical situation anxiety", labelWord: "W" },
      { answer: "+ Mustard", labelWord: "X" }
    ],
  },
];
